### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pehbehbeh** [huangdijia/laravel-horizon-restart#3]
This package does not contain a license file, but mentions [MIT in the `composer.json`](https://github.com/huangdijia/laravel-horizon-restart/blob/73d57979973fe1edb3d5f1cc1250ef20dbd2c733/composer.json#L11). Can we safely assume, that this is correct?

Maybe you can add a license file to the repo root to make things clearer? Licenses are also [highlighted by GitHub](https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/).

**Comment by huangdijia** [comment]
OK now

**Comment by pehbehbeh** [comment]
Thanks!
